### PR TITLE
Preload the translation helpers

### PR DESCRIPTION
**Pull request by amieiro**
## Problem

When you want to start translating, and you open the first row, an AJAX query is fired to get the translation helpers. This query needs some time to be transmitted and showed, so you don't see the content immediately. 

## Solution

This PR adds a local cache for the translation helpers, in 1 local variable:
* For the first row when the page loads, so when the user opens the first row, she gets the translation helpers immediately.
* For the next row, when she opens a row, so when the user opens the next row, she gets the translation helpers immediately.

We only cache what we believe to be the most likely row to be opened next, not all of them, as this avoids making excessive AJAX calls. 

## Testing instructions

I suggest to made, at least, 2 tests with:
* a table with a few strings to translate. You need to review that we only made one request per row (original string).
* a table with only a string to translate. You need to review that we only made one request.

To make your work easier, you can filter in the "Network" tab the "?nohc" text, because all the AJAX queries have this text at the end of the URL.

image

### CODE REVIEW

**Comment by akirk** [comment]
I've tested it and it works but one scenario could be handled better:

When the next tabs are already loading but haven't finished loading then it will load the next tabs twice. You should also keep track when you started loading so that when you switch to that row it would not trigger another load but just let the first load complete.

**Comment by amieiro** [comment]
> I've tested it and it works but one scenario could be handled better:
> 
> When the next tabs are already loading but haven't finished loading then it will load the next tabs twice. You should also keep track when you started loading so that when you switch to that row it would not trigger another load but just let the first load complete.

I have added an empty reply to the array before making the AJAX query to avoid making the same call more than one time.

**Comment by trymebytes** [comment]
Please rebase again

**Comment by amieiro** [comment]
> Please rebase again

@trymebytes done!

**Review by akirk — CHANGES_REQUESTED** [review]
I testssd this in Firefox and I do see preloading happening but I run into the following two issues:

1. The tabs are always truncated:
Screenshot 2023-06-22 at 10 37 18

2. When I navigate to a row while it is preloading, it stays empty:
tab-not-loading

When I navigate around I can get it to display but not very easily:
tab-not-loading2

**Comment by amieiro** [comment]
@akirk good catch for the row opened before having the data. I have resolved this problem. I will address the tabs' problem in another PR.

**Comment by akirk** [comment]
Nice, I tested it and it works. Is adding a loading indicator outside of the scope of this PR or can it be done easily?

**Review by akirk — APPROVED** [review]
Talked to @amieiro, we'll add the spinner to the upcoming tabs refactor PR.

**Pull request merged**
