### PR TITLE
Require topic

### PR DESCRIPTION
**Pull request by trymebytes**
Make the Topic required and show error message if selected option has empty value
image

### CODE REVIEW

**Comment by akirk** [comment]
I wonder whether the introduction of another meta value is necessary. Couldn't we just use the reject reason?

**Review by amieiro — COMMENTED** [review]
I have reviewed it on my local machine with the last stable version of Chrome and Firefox and it works fine for me.

**Comment by akirk** [comment]
For reference, we force the HTML5 format for any theme and remove the `novalidate` attribute because [WordPress Core has reasons to keep it there](https://core.trac.wordpress.org/ticket/47595).

**Review by akirk — APPROVED** [review]
Works for me!

**Pull request merged**
