### PR TITLE
Show dropdown of glossary words extracted from the original

### PR DESCRIPTION
**Pull request by trymebytes**
We are trying to shorten the user journey when rejecting with feedback. As a result, when approver selects "Glossary" as the reason for rejection, we show a list of checkboxes of Glossary items that appear in the original of which the approver can select which of them is wrong for the current translation(s).

Mockup:

Screenshot 2022-09-20 at 10 12 20

We don't store this as additional metadata but generate an English text. It would be interesting to provide a similar hover functionality as in the original text.

### CODE REVIEW

**Review by amieiro — CHANGES_REQUESTED** [review]
I am testing this PR in a local GlotPress and I think we have to modify some items:


a) Remove the dots (1) and add some space between the checkbox and the text, like the previous checkboxes. 

image

b) When I select more than one checkbox, we have the same checkboxes with the glossary terms repeated the same times the number of checkboxes selected. We need the glossary items only once.

image

c) When I deselect all checkboxes, the glossary checkboxes are shown.

image


d) I think we only should show the glossary checkboxes when the user selects the "Glossary" checkbox. Is this ok for you?

e) I think it would be interesting to add a subtitle before the new checkboxes, showing these are the words we have in the local glossary.

image

f) Are we going to generate the comment automatically with the checkboxes?

**Comment by akirk** [comment]
> f) Are we going to generate the comment automatically with the checkboxes?

It should as I see in the source here: https://github.com/GlotPress/gp-translation-helpers/pull/118/files#diff-c7e3786a8c23a15f89c3a14a9c190b178725a738dcc04797b405d401f4cf67bcR235

I wonder if we could also actually display the glossary text (that appears in the popover), maybe also in a popover or on the side but truncated?

**Comment by trymebytes** [comment]
@amieiro Regarding the styling issue, I don't seem to have the same issues, kindly do a hard reload and see if it changes, here's how it looks for me
image

I have fixed `(b) `the glossary list is only displayed when the Glossary checkbox is checked.

**Comment by akirk** [comment]
I think adding cache busters for the scripts would be good.

**Comment by akirk** [comment]
Cache busters are no longer necessary because we use [`filemtime` now](https://github.com/GlotPress/gp-translation-helpers/blob/21838fa4a60e4ecb880b6d30b5174d0750c8ac42/includes/class-gp-translation-helpers.php#L74).

**Pull request merged**
