### PR TITLE
Improve Bulk Reject UI

### PR DESCRIPTION
**Pull request by trymebytes**
## Problem
This PR attempts to improve the look for the bulk reject form and also fix style variations in different environments.
At the moment, here's how the popover looks in a local GlotPress environment.
image

Here's how it looks in a local translate.wp.org environment
image

In this PR, the popover now looks like this
### Local GlotPress Install
image

### translate.wp.org environment 

image

### CODE REVIEW

**Comment by amieiro** [comment]
It looks good to me, both at translate.w.org and at GlotPress. 

One improvement. When I open the popover, the close button has the focus. Can you remove it? 

### translate.w.org

image

### GlotPress

image

**Comment by trymebytes** [comment]
Done, blue border removed.

**Comment by trymebytes** [comment]
I've just checked again and it displays well on translate.w.org. Please confirm that you have pulled recent commits in the translate.w.org environement.

**Comment by amieiro** [comment]
It works fine. I was testing it in the incorrect environment. It is ready to merge.

**Review by amieiro — APPROVED** [review]

**Pull request merged**
