### PR TITLE
Fix return type error

### LINKED ISSUE #204: Uncaught TypeError: Return value of WPorg_GlotPress_Notifications::get_project_from_original_id() must be an instance of GP_Project
E_ERROR: Uncaught TypeError: Return value of WPorg_GlotPress_Notifications::get_project_from_original_id() must be an instance of GP_Project, bool returned in /home/wporg/public_html/wp-content/plugins/gp-translation-helpers/includes/class-wporg-notifications.php:526

https://wordpress.slack.com/archives/G02QB4059/p1700015109914449

### PR DESCRIPTION
**Pull request by trymebytes**
Fixes #204

### CODE REVIEW

**Review by akirk — APPROVED** [review]
Looks good to me, thanks!

**Review by akirk — CHANGES_REQUESTED** [review]
Oh, I think there is one projects check missing but I cannot highlight it. In line 526 of includes/class-wporg-notifications.php

**Comment by trymebytes** [comment]
> Oh, I think there is one projects check missing but I cannot highlight it. In line 526 of includes/class-wporg-notifications.php

I think since we already checked if the $original has a value then a project must exist. However, if a project doesn't exist then this [line](https://github.com/GlotPress/gp-translation-helpers/blob/67a0059ff5c8b2257d8910f67ebcd2acb33f8b8c/includes/class-wporg-notifications.php#L535) will return false.

**Comment by akirk** [comment]
Yes but in the [if above](https://github.com/GlotPress/gp-translation-helpers/blob/67a0059ff5c8b2257d8910f67ebcd2acb33f8b8c/includes/class-wporg-notifications.php#L532C21-L532C29) we'll try to access a property on null.

**Review by akirk — APPROVED** [review]

**Comment by trymebytes** [comment]
Thank you!

**Pull request merged**
