### PR TITLE
Notification on rejection

### PR DESCRIPTION
**Pull request by amieiro**
## Problem

When a validator rejects one or several strings, the plugin didn't send a notification to the translator.

## Solution

This PR sends a notification to the translator when one or several strings are rejected.

## Testing instructions

Add some translations with one user (user 1).

Reject one translation with a different user (user 2).

image

The translator (user 1) will get a notification.

image

Reject some translations in a bulk translation (user 2).

image

The translator (user 1) will get a notification with 2 URL, without the original and translation strings, because in this situation we have two or more strings.
 
image

### CODE REVIEW

**Comment by trymebytes** [comment]
There's been a recent merge to main, please fix merge conflicts.

**Comment by amieiro** [comment]
> There's been a recent merge to branch `main`, please fix merge conflicts.

Done!!

**Review by trymebytes — APPROVED** [review]
Looks good to me, works as described. I'm wondering if it's useful to link to the exact comment on the discussions page. Something like - http://glotpress.test/projects/wp/dev/7/#comment-118


Screenshot 2022-05-10 at 14 46 26

**Comment by amieiro** [comment]
> Looks good to me, works as described. I'm wondering if it's useful to link to the exact comment on the discussions page. Something like - http://glotpress.test/projects/wp/dev/7/#comment-118
> 

Good point 👍 . I think it is interesting to link to the correct anchor, so this improves the work for the reader. I will improve this in another PR, in the URL list (Point 2 in the screenshot). We can do this on (1) when we don't have bulk rejections, because they have 2 or more links. 

image

**Comment by trymebytes** [comment]
Tested and works as expected!

**Pull request merged**
